Repository semilleroCV/deep-learning-notes, pull requests merged in 2024-08, with the labels that each got.

#22 nlp stanford badge repair attempt
  automation/autogenerate_notebooks_table.py
Labels: fix

#20 Add ViT architecture
  automation/notebooks-table-data.csv
  notebooks/architectures/vit.ipynb
Labels: architecture

#23 Fix/logos base64
  automation/autogenerate_notebooks_table.py
  automation/logos.py
Labels: fix

#25 remove dot parent import
  automation/autogenerate_notebooks_table.py
Labels: fix

#21 add module multi-head-attention
  automation/notebooks-table-data.csv
  notebooks/modules/multihead-self-attention.ipynb
Labels: module
